## Imports

In [1]:
import keras
from keras.models import Sequential
from keras.layers import Dense
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from statistics import mean, stdev

Using TensorFlow backend.
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:521: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:522: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])

## Building base model

In [2]:
def regression_model():
    model = Sequential()
    model.add(Dense(10, activation='relu', input_shape=(8,)))
    model.add(Dense(10, activation='relu'))
    model.add(Dense(1))
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

In [3]:
model = regression_model()

In [4]:
def predict() :
    return model.predict(X_test)
def calculate_mse() :
    return mean_squared_error(Y_test,Y_predicted)

In [5]:
report = pd.DataFrame(columns = ['Assignment','Model, data and epoch information', 'MSE'])

## Data import and cleaning

In [6]:
concrete_data = pd.read_csv('https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0101EN/labs/data/concrete_data.csv')
concrete_data.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

In [7]:
concrete_data_columns = concrete_data.columns
X = concrete_data[concrete_data_columns[concrete_data_columns != 'Strength']]
Y = concrete_data['Strength']
X.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360

In [8]:
Y.head()

0    79.99
1    61.89
2    40.27
3    41.05
4    44.30
Name: Strength, dtype: float64

# Part A: Base model

## Part a1: Split data

In [9]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3)

## Part a2: Training with 50 epochs

In [10]:
model.fit(X_train, Y_train, validation_split=0.3, epochs=50, verbose=2)

Train on 504 samples, validate on 217 samples
Epoch 1/50
 - 1s - loss: 1563.3583 - val_loss: 951.7475
Epoch 2/50
 - 0s - loss: 1000.5841 - val_loss: 846.2268
Epoch 3/50
 - 0s - loss: 844.1724 - val_loss: 717.8640
Epoch 4/50
 - 0s - loss: 735.7938 - val_loss: 626.5228
Epoch 5/50
 - 0s - loss: 641.8014 - val_loss: 546.6196
Epoch 6/50
 - 0s - loss: 556.2844 - val_loss: 479.0190
Epoch 7/50
 - 0s - loss: 486.4604 - val_loss: 424.3351
Epoch 8/50
 - 0s - loss: 431.5009 - val_loss: 380.6870
Epoch 9/50
 - 0s - loss: 388.4266 - val_loss: 349.2875
Epoch 10/50
 - 0s - loss: 358.8833 - val_loss: 325.9206
Epoch 11/50
 - 0s - loss: 335.3778 - val_loss: 308.4434
Epoch 12/50
 - 0s - loss: 318.2562 - val_loss: 293.1476
Epoch 13/50
 - 0s - loss: 304.8174 - val_loss: 281.6510
Epoch 14/50
 - 0s - loss: 296.6134 - val_loss: 271.7176
Epoch 15/50
 - 0s - loss: 291.7897 - val_loss: 263.9038
Epoch 16/50
 - 0s - loss: 280.0478 - val_loss: 256.5885
Epoch 17/50
 - 0s - loss: 271.8962 - val_loss: 250.5914
Epoch 18/50
 - 0s - loss: 268.1445 - val_loss: 245.5632
Epoch 19/50
 - 0s - loss: 261.1027 - val_loss: 240.6743
Epoch 20/50
 - 0s - loss: 257.0466 - val_loss: 237.0096
Epoch 21/50
 - 0s - loss: 252.5458 - val_loss: 232.2327
Epoch 22/50
 - 0s - loss: 250.9177 - val_loss: 228.4022
Epoch 23/50
 - 0s - loss: 247.4529 - val_loss: 224.8921
Epoch 24/50
 - 0s - loss: 249.7504 - val_loss: 225.2817
Epoch 25/50
 - 0s - loss: 248.5345 - val_loss: 220.8533
Epoch 26/50
 - 0s - loss: 235.0488 - val_loss: 216.2757
Epoch 27/50
 - 0s - loss: 231.9835 - val_loss: 213.2428
Epoch 28/50
 - 0s - loss: 227.7075 - val_loss: 212.3615
Epoch 29/50
 - 0s - loss: 225.7828 - val_loss: 208.2955
Epoch 30/50
 - 0s - loss: 224.7998 - val_loss: 210.3968
Epoch 31/50
 - 0s - loss: 223.1505 - val_loss: 203.8641
Epoch 32/50
 - 0s - loss: 217.0841 - val_loss: 202.8558
Epoch 33/50
 - 0s - loss: 212.7984 - val_loss: 199.5390
Epoch 34/50
 - 0s - loss: 212.3520 - val_loss: 198.0664
Epoch 35/50
 - 0s - loss: 208.0642 - val_loss: 195.9435
Epoch 36/50
 - 0s - loss: 205.1031 - val_loss: 194.3326
Epoch 37/50
 - 0s - loss: 203.2280 - val_loss: 192.9792
Epoch 38/50
 - 0s - loss: 201.0407 - val_loss: 192.3323
Epoch 39/50
 - 0s - loss: 198.6033 - val_loss: 190.0534
Epoch 40/50
 - 0s - loss: 197.6394 - val_loss: 191.2637
Epoch 41/50
 - 0s - loss: 196.3789 - val_loss: 193.0345
Epoch 42/50
 - 0s - loss: 193.5521 - val_loss: 186.3520
Epoch 43/50
 - 0s - loss: 190.8194 - val_loss: 185.5453
Epoch 44/50
 - 0s - loss: 189.1974 - val_loss: 183.0702
Epoch 45/50
 - 0s - loss: 185.5925 - val_loss: 182.0377
Epoch 46/50
 - 0s - loss: 183.3929 - val_loss: 181.5597
Epoch 47/50
 - 0s - loss: 182.8998 - val_loss: 181.7606
Epoch 48/50
 - 0s - loss: 181.3087 - val_loss: 180.7297
Epoch 49/50
 - 0s - loss: 177.6066 - val_loss: 177.3867
Epoch 50/50
 - 0s - loss: 177.9128 - val_loss: 180.1205

## Part a3: Evaluation

In [11]:
Y_predicted = predict()
mse = calculate_mse()
report.loc[0] = ['A2', 'Single run, one hidden layer, 50 epochs', round(mse,2)]
print('The mean square error' , round(mse))

The mean square error 193

## Part a4: Repeat 50 times

In [12]:
mses = []
for i in range(50):
    model = regression_model()
    X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3)
    model.fit(X_train, Y_train, validation_split=0.3, epochs=50, verbose=0)
    Y_predicted = predict()
    mse = calculate_mse()
    mses.append(mse)
    print('Run', i + 1 , 'has an mse of', round(mse,2))

Run 1 has an mse of 85.5
Run 2 has an mse of 121.06
Run 3 has an mse of 198.19
Run 4 has an mse of 236.21
Run 5 has an mse of 169.14
Run 6 has an mse of 133.97
Run 7 has an mse of 125.53
Run 8 has an mse of 147.86
Run 9 has an mse of 746.85
Run 10 has an mse of 124.4
Run 11 has an mse of 174.96
Run 12 has an mse of 168.09
Run 13 has an mse of 165.38
Run 14 has an mse of 360.89
Run 15 has an mse of 132.35
Run 16 has an mse of 244.56
Run 17 has an mse of 133.04
Run 18 has an mse of 103.65
Run 19 has an mse of 299.75
Run 20 has an mse of 106.45
Run 21 has an mse of 165.23
Run 22 has an mse of 103.8
Run 23 has an mse of 237.29
Run 24 has an mse of 177.08
Run 25 has an mse of 115.07
Run 26 has an mse of 94.48
Run 27 has an mse of 164.12
Run 28 has an mse of 158.16
Run 29 has an mse of 93.14
Run 30 has an mse of 146.53
Run 31 has an mse of 296.18
Run 32 has an mse of 163.48
Run 33 has an mse of 187.05
Run 34 has an mse of 477.26
Run 35 has an mse of 101.58
Run 36 has an mse of 132.24
Run 37 has an mse of 102.78
Run 38 has an mse of 119.22
Run 39 has an mse of 365.4
Run 40 has an mse of 179.59
Run 41 has an mse of 139.65
Run 42 has an mse of 215.64
Run 43 has an mse of 116.82
Run 44 has an mse of 238.08
Run 45 has an mse of 108.2
Run 46 has an mse of 129.95
Run 47 has an mse of 131.08
Run 48 has an mse of 108.63
Run 49 has an mse of 169.97
Run 50 has an mse of 100.55

In [13]:
msesmean = mean(mses)
msesstd = stdev(mses)
report.loc[1] = ['A4', 'Avarage of 50 runs, one hidden layer, 50 epochs', round(msesmean)]
print('The mean of mean square errors' , str(round(msesmean,2)))
print('Standard deviation of mean square errors' , str(round(msesstd,2)))

The mean of mean square errors 180.32
Standard deviation of mean square errors 113.44

# Part B: Normalize the data

# Part b1: Normalizing

In [14]:
Xnorm = X - X.mean() / X.std()

In [15]:
X_trainnorm, X_testnorm, Y_trainnorm, Y_testnorm = train_test_split(Xnorm, Y, test_size=0.3)

In [16]:
model.fit(X_trainnorm, Y_trainnorm, validation_split=0.3, epochs=50, verbose=2)

Train on 504 samples, validate on 217 samples
Epoch 1/50
 - 0s - loss: 87.7938 - val_loss: 93.7028
Epoch 2/50
 - 0s - loss: 85.8636 - val_loss: 94.0782
Epoch 3/50
 - 0s - loss: 84.8998 - val_loss: 95.1186
Epoch 4/50
 - 0s - loss: 84.4742 - val_loss: 94.3974
Epoch 5/50
 - 0s - loss: 82.4792 - val_loss: 95.3461
Epoch 6/50
 - 0s - loss: 83.0647 - val_loss: 96.2619
Epoch 7/50
 - 0s - loss: 80.1478 - val_loss: 95.5567
Epoch 8/50
 - 0s - loss: 79.9169 - val_loss: 97.9563
Epoch 9/50
 - 0s - loss: 80.0001 - val_loss: 96.1516
Epoch 10/50
 - 0s - loss: 80.0931 - val_loss: 95.0494
Epoch 11/50
 - 0s - loss: 80.9215 - val_loss: 97.6732
Epoch 12/50
 - 0s - loss: 78.1842 - val_loss: 93.0822
Epoch 13/50
 - 0s - loss: 77.6599 - val_loss: 92.5088
Epoch 14/50
 - 0s - loss: 76.7137 - val_loss: 94.4041
Epoch 15/50
 - 0s - loss: 75.0531 - val_loss: 97.1132
Epoch 16/50
 - 0s - loss: 79.3917 - val_loss: 95.2341
Epoch 17/50
 - 0s - loss: 82.1150 - val_loss: 109.1614
Epoch 18/50
 - 0s - loss: 78.1556 - val_loss: 108.9700
Epoch 19/50
 - 0s - loss: 81.0419 - val_loss: 90.3538
Epoch 20/50
 - 0s - loss: 73.4659 - val_loss: 91.2694
Epoch 21/50
 - 0s - loss: 72.9573 - val_loss: 90.1878
Epoch 22/50
 - 0s - loss: 71.0715 - val_loss: 90.9478
Epoch 23/50
 - 0s - loss: 71.1062 - val_loss: 99.4125
Epoch 24/50
 - 0s - loss: 71.3629 - val_loss: 93.3679
Epoch 25/50
 - 0s - loss: 70.1255 - val_loss: 88.1434
Epoch 26/50
 - 0s - loss: 74.5014 - val_loss: 90.2925
Epoch 27/50
 - 0s - loss: 72.0207 - val_loss: 88.9242
Epoch 28/50
 - 0s - loss: 68.4995 - val_loss: 89.4263
Epoch 29/50
 - 0s - loss: 69.1212 - val_loss: 90.3768
Epoch 30/50
 - 0s - loss: 70.8159 - val_loss: 89.3541
Epoch 31/50
 - 0s - loss: 69.1736 - val_loss: 87.8923
Epoch 32/50
 - 0s - loss: 67.0832 - val_loss: 90.3315
Epoch 33/50
 - 1s - loss: 67.4864 - val_loss: 89.1579
Epoch 34/50
 - 0s - loss: 66.8115 - val_loss: 87.8491
Epoch 35/50
 - 0s - loss: 68.1790 - val_loss: 86.5734
Epoch 36/50
 - 0s - loss: 65.7776 - val_loss: 90.7041
Epoch 37/50
 - 0s - loss: 69.2050 - val_loss: 88.5284
Epoch 38/50
 - 0s - loss: 66.1108 - val_loss: 89.8316
Epoch 39/50
 - 0s - loss: 65.1999 - val_loss: 86.5112
Epoch 40/50
 - 0s - loss: 65.6750 - val_loss: 84.3074
Epoch 41/50
 - 0s - loss: 63.9487 - val_loss: 86.0552
Epoch 42/50
 - 0s - loss: 64.4338 - val_loss: 86.3869
Epoch 43/50
 - 0s - loss: 64.6565 - val_loss: 84.0036
Epoch 44/50
 - 0s - loss: 65.1404 - val_loss: 88.1474
Epoch 45/50
 - 0s - loss: 65.3281 - val_loss: 82.9037
Epoch 46/50
 - 0s - loss: 66.4283 - val_loss: 88.1768
Epoch 47/50
 - 0s - loss: 63.7701 - val_loss: 83.7635
Epoch 48/50
 - 0s - loss: 62.8639 - val_loss: 82.5067
Epoch 49/50
 - 0s - loss: 65.5744 - val_loss: 84.3080
Epoch 50/50
 - 0s - loss: 64.0720 - val_loss: 83.3186

In [17]:
Y_predicted = predict()
mse = calculate_mse()
report.loc[2] = ['B1', 'Single run, normalized data, one hidden layer, 50 epochs', round(mse)]
print('The mean square error' , round(mse))

The mean square error 78

In [18]:
msesnorm = []
for i in range(50):
    model = regression_model()
    X_trainnorm, X_testnorm, Y_trainnorm, Y_testnorm = train_test_split(Xnorm, Y, test_size=0.3)
    model.fit(X_trainnorm, Y_trainnorm, validation_split=0.3, epochs=50, verbose=0)
    Y_predicted = predict()
    msenorm = calculate_mse()
    msesnorm.append(msenorm)
    print('Run', i + 1 , 'has an mse of', round(msenorm,2))

Run 1 has an mse of 113.7
Run 2 has an mse of 101.65
Run 3 has an mse of 308.34
Run 4 has an mse of 151.97
Run 5 has an mse of 91.54
Run 6 has an mse of 113.64
Run 7 has an mse of 642.44
Run 8 has an mse of 224.95
Run 9 has an mse of 117.3
Run 10 has an mse of 142.76
Run 11 has an mse of 143.99
Run 12 has an mse of 184.1
Run 13 has an mse of 101.08
Run 14 has an mse of 99.41
Run 15 has an mse of 215.48
Run 16 has an mse of 157.51
Run 17 has an mse of 256.58
Run 18 has an mse of 115.64
Run 19 has an mse of 113.85
Run 20 has an mse of 219.13
Run 21 has an mse of 364.93
Run 22 has an mse of 248.66
Run 23 has an mse of 209.03
Run 24 has an mse of 99.91
Run 25 has an mse of 1615.19
Run 26 has an mse of 197.93
Run 27 has an mse of 167.57
Run 28 has an mse of 114.74
Run 29 has an mse of 173.98
Run 30 has an mse of 103.3
Run 31 has an mse of 131.26
Run 32 has an mse of 286.28
Run 33 has an mse of 242.2
Run 34 has an mse of 135.09
Run 35 has an mse of 127.29
Run 36 has an mse of 164.38
Run 37 has an mse of 82.11
Run 38 has an mse of 191.56
Run 39 has an mse of 183.46
Run 40 has an mse of 239.64
Run 41 has an mse of 96.33
Run 42 has an mse of 182.63
Run 43 has an mse of 164.62
Run 44 has an mse of 116.69
Run 45 has an mse of 116.58
Run 46 has an mse of 300.86
Run 47 has an mse of 101.56
Run 48 has an mse of 209.19
Run 49 has an mse of 144.04
Run 50 has an mse of 138.55

In [19]:
msesmeannorm = mean(msesnorm)
msesstdnorm = stdev(msesnorm)
report.loc[3] = ['B2', 'Avarage of 50 runs, normalized data, one hidden layer, 50 epochs', round(msesmeannorm)]
print('The mean of mean square errors' , str(round(msesmeannorm,2)))
print('Standard deviation of mean square errors' , str(round(msesstdnorm,2)))

The mean of mean square errors 205.29
Standard deviation of mean square errors 223.76

# Part C, Increase the number of epochs

In [20]:
model.fit(X_trainnorm, Y_trainnorm, validation_split=0.3, epochs=100, verbose=2)
Y_predicted = predict()
mse = calculate_mse()
#mse = mean_squared_error(Y_test,Y_predicted)
print('The mean square error' , round(mse))
report.loc[5] = ['C1', 'Single run, normalized data, one hidden layer, 100 epochs', round(mse,2)]

Train on 504 samples, validate on 217 samples
Epoch 1/100
 - 0s - loss: 137.9003 - val_loss: 132.2202
Epoch 2/100
 - 0s - loss: 135.4247 - val_loss: 129.0387
Epoch 3/100
 - 0s - loss: 133.5281 - val_loss: 127.8460
Epoch 4/100
 - 0s - loss: 132.1842 - val_loss: 124.2896
Epoch 5/100
 - 0s - loss: 130.2650 - val_loss: 122.0975
Epoch 6/100
 - 0s - loss: 126.8833 - val_loss: 120.0696
Epoch 7/100
 - 0s - loss: 127.1473 - val_loss: 118.5064
Epoch 8/100
 - 0s - loss: 122.4199 - val_loss: 116.7996
Epoch 9/100
 - 0s - loss: 121.9870 - val_loss: 115.1011
Epoch 10/100
 - 0s - loss: 121.1834 - val_loss: 112.9262
Epoch 11/100
 - 0s - loss: 117.6923 - val_loss: 110.7240
Epoch 12/100
 - 0s - loss: 116.7264 - val_loss: 109.1767
Epoch 13/100
 - 0s - loss: 114.6302 - val_loss: 107.9547
Epoch 14/100
 - 0s - loss: 115.0415 - val_loss: 106.6299
Epoch 15/100
 - 0s - loss: 113.2348 - val_loss: 104.7272
Epoch 16/100
 - 0s - loss: 111.0583 - val_loss: 102.9588
Epoch 17/100
 - 0s - loss: 110.0948 - val_loss: 102.2605
Epoch 18/100
 - 0s - loss: 109.1783 - val_loss: 101.7571
Epoch 19/100
 - 0s - loss: 109.6137 - val_loss: 99.4508
Epoch 20/100
 - 0s - loss: 107.4073 - val_loss: 98.0337
Epoch 21/100
 - 0s - loss: 105.1661 - val_loss: 97.9697
Epoch 22/100
 - 0s - loss: 105.6879 - val_loss: 96.6100
Epoch 23/100
 - 0s - loss: 103.5930 - val_loss: 95.6445
Epoch 24/100
 - 0s - loss: 102.6985 - val_loss: 93.9323
Epoch 25/100
 - 0s - loss: 103.7832 - val_loss: 93.4176
Epoch 26/100
 - 0s - loss: 100.6022 - val_loss: 91.8030
Epoch 27/100
 - 0s - loss: 99.7034 - val_loss: 92.2766
Epoch 28/100
 - 0s - loss: 99.6009 - val_loss: 90.6498
Epoch 29/100
 - 0s - loss: 98.9547 - val_loss: 91.6414
Epoch 30/100
 - 0s - loss: 98.9194 - val_loss: 92.7771
Epoch 31/100
 - 0s - loss: 99.6725 - val_loss: 88.9764
Epoch 32/100
 - 0s - loss: 100.1241 - val_loss: 95.7623
Epoch 33/100
 - 0s - loss: 97.9922 - val_loss: 95.7532
Epoch 34/100
 - 0s - loss: 97.7003 - val_loss: 86.1294
Epoch 35/100
 - 0s - loss: 95.8441 - val_loss: 86.1397
Epoch 36/100
 - 0s - loss: 93.7971 - val_loss: 85.8272
Epoch 37/100
 - 0s - loss: 94.1839 - val_loss: 87.7225
Epoch 38/100
 - 0s - loss: 92.7522 - val_loss: 84.0741
Epoch 39/100
 - 0s - loss: 91.5773 - val_loss: 83.6820
Epoch 40/100
 - 0s - loss: 92.5594 - val_loss: 86.1868
Epoch 41/100
 - 0s - loss: 93.2086 - val_loss: 84.3808
Epoch 42/100
 - 0s - loss: 91.9578 - val_loss: 81.3783
Epoch 43/100
 - 0s - loss: 92.4310 - val_loss: 82.8561
Epoch 44/100
 - 0s - loss: 90.6183 - val_loss: 80.7220
Epoch 45/100
 - 0s - loss: 89.1089 - val_loss: 83.0138
Epoch 46/100
 - 0s - loss: 90.1062 - val_loss: 80.0151
Epoch 47/100
 - 0s - loss: 87.9483 - val_loss: 80.2289
Epoch 48/100
 - 0s - loss: 87.3769 - val_loss: 82.8225
Epoch 49/100
 - 0s - loss: 90.3300 - val_loss: 78.5376
Epoch 50/100
 - 0s - loss: 86.4794 - val_loss: 78.2634
Epoch 51/100
 - 0s - loss: 85.9359 - val_loss: 81.2677
Epoch 52/100
 - 0s - loss: 89.8541 - val_loss: 78.5088
Epoch 53/100
 - 0s - loss: 88.6498 - val_loss: 80.2165
Epoch 54/100
 - 0s - loss: 86.4141 - val_loss: 77.6288
Epoch 55/100
 - 0s - loss: 84.9612 - val_loss: 78.8424
Epoch 56/100
 - 0s - loss: 84.6994 - val_loss: 76.7693
Epoch 57/100
 - 0s - loss: 83.9433 - val_loss: 76.5904
Epoch 58/100
 - 0s - loss: 84.2399 - val_loss: 77.7897
Epoch 59/100
 - 0s - loss: 84.0312 - val_loss: 79.5826
Epoch 60/100
 - 0s - loss: 84.1139 - val_loss: 76.3810
Epoch 61/100
 - 0s - loss: 83.4339 - val_loss: 75.2692
Epoch 62/100
 - 0s - loss: 81.8574 - val_loss: 79.0491
Epoch 63/100
 - 0s - loss: 85.0533 - val_loss: 78.0716
Epoch 64/100
 - 0s - loss: 82.3566 - val_loss: 74.9032
Epoch 65/100
 - 0s - loss: 83.8507 - val_loss: 73.7849
Epoch 66/100
 - 0s - loss: 82.1685 - val_loss: 78.3894
Epoch 67/100
 - 0s - loss: 81.7069 - val_loss: 75.2774
Epoch 68/100
 - 0s - loss: 80.5446 - val_loss: 72.8884
Epoch 69/100
 - 0s - loss: 81.2013 - val_loss: 74.3082
Epoch 70/100
 - 0s - loss: 81.3977 - val_loss: 75.1214
Epoch 71/100
 - 0s - loss: 81.0536 - val_loss: 76.5599
Epoch 72/100
 - 0s - loss: 82.1128 - val_loss: 78.3972
Epoch 73/100
 - 0s - loss: 79.8161 - val_loss: 71.7051
Epoch 74/100
 - 0s - loss: 81.5684 - val_loss: 71.5961
Epoch 75/100
 - 0s - loss: 81.3466 - val_loss: 79.9549
Epoch 76/100
 - 0s - loss: 80.4680 - val_loss: 74.1765
Epoch 77/100
 - 0s - loss: 79.5502 - val_loss: 71.3273
Epoch 78/100
 - 0s - loss: 79.8993 - val_loss: 70.7373
Epoch 79/100
 - 0s - loss: 78.6713 - val_loss: 70.7807
Epoch 80/100
 - 0s - loss: 80.6657 - val_loss: 70.1387
Epoch 81/100
 - 0s - loss: 78.7351 - val_loss: 70.4093
Epoch 82/100
 - 0s - loss: 78.5344 - val_loss: 70.5504
Epoch 83/100
 - 0s - loss: 77.6897 - val_loss: 70.1870
Epoch 84/100
 - 0s - loss: 78.5813 - val_loss: 71.3325
Epoch 85/100
 - 0s - loss: 79.5602 - val_loss: 69.7566
Epoch 86/100
 - 0s - loss: 77.3567 - val_loss: 68.7526
Epoch 87/100
 - 0s - loss: 77.8847 - val_loss: 72.4083
Epoch 88/100
 - 0s - loss: 76.5036 - val_loss: 69.4125
Epoch 89/100
 - 0s - loss: 77.1639 - val_loss: 73.8983
Epoch 90/100
 - 0s - loss: 78.8276 - val_loss: 69.7021
Epoch 91/100
 - 0s - loss: 78.0045 - val_loss: 72.2905
Epoch 92/100
 - 0s - loss: 76.8323 - val_loss: 68.4178
Epoch 93/100
 - 0s - loss: 79.6821 - val_loss: 71.3483
Epoch 94/100
 - 0s - loss: 80.0313 - val_loss: 67.4082
Epoch 95/100
 - 0s - loss: 78.9971 - val_loss: 67.6551
Epoch 96/100
 - 0s - loss: 74.9849 - val_loss: 78.1622
Epoch 97/100
 - 0s - loss: 76.9801 - val_loss: 67.0806
Epoch 98/100
 - 0s - loss: 75.9336 - val_loss: 66.7108
Epoch 99/100
 - 0s - loss: 77.7751 - val_loss: 70.0323
Epoch 100/100
 - 0s - loss: 77.7022 - val_loss: 66.4161
The mean square error 87

In [21]:
msesnorm = []
for i in range(50):
    model = regression_model()
    X_trainnorm, X_testnorm, Y_trainnorm, Y_testnorm = train_test_split(Xnorm, Y, test_size=0.3)
    model.fit(X_trainnorm, Y_trainnorm, validation_split=0.3, epochs=50, verbose=0)
    Y_predicted = predict()
    msenorm = calculate_mse()
    msesnorm.append(msenorm)
    print('Run', i + 1 , 'has an mse of', round(msenorm,2))

Run 1 has an mse of 381.48
Run 2 has an mse of 78.02
Run 3 has an mse of 514.77
Run 4 has an mse of 163.56
Run 5 has an mse of 386.19
Run 6 has an mse of 205.88
Run 7 has an mse of 121.48
Run 8 has an mse of 157.43
Run 9 has an mse of 118.91
Run 10 has an mse of 167.78
Run 11 has an mse of 100.11
Run 12 has an mse of 111.5
Run 13 has an mse of 142.02
Run 14 has an mse of 202.59
Run 15 has an mse of 116.58
Run 16 has an mse of 115.37
Run 17 has an mse of 220.09
Run 18 has an mse of 205.07
Run 19 has an mse of 113.16
Run 20 has an mse of 93.78
Run 21 has an mse of 236.4
Run 22 has an mse of 127.99
Run 23 has an mse of 130.81
Run 24 has an mse of 103.57
Run 25 has an mse of 490.86
Run 26 has an mse of 186.43
Run 27 has an mse of 129.79
Run 28 has an mse of 149.86
Run 29 has an mse of 154.02
Run 30 has an mse of 148.27
Run 31 has an mse of 251.6
Run 32 has an mse of 146.0
Run 33 has an mse of 310.77
Run 34 has an mse of 124.14
Run 35 has an mse of 118.84
Run 36 has an mse of 99.27
Run 37 has an mse of 115.64
Run 38 has an mse of 124.8
Run 39 has an mse of 148.15
Run 40 has an mse of 123.09
Run 41 has an mse of 772.03
Run 42 has an mse of 95.02
Run 43 has an mse of 185.17
Run 44 has an mse of 102.96
Run 45 has an mse of 103.49
Run 46 has an mse of 101.47
Run 47 has an mse of 227.41
Run 48 has an mse of 288.34
Run 49 has an mse of 126.95
Run 50 has an mse of 291.8

In [22]:
msesmeannorm = mean(msesnorm)
msesstdnorm = stdev(msesnorm)
report.loc[4] = ['C2', 'Avarage of 50 runs, normalized data, one hidden layer, 100 epochs', msesmeannorm]
print('The mean of mean square errors' , str(round(msesmeannorm,2)))
print('Standard deviation of mean square errors' , str(round(msesstdnorm,2)))

The mean of mean square errors 188.61
Standard deviation of mean square errors 128.98

# Part D: Increase the number of hidden layers

In [23]:
def l3_regression_model():
    model = Sequential()
    model.add(Dense(10, activation='relu', input_shape=(8,)))
    model.add(Dense(10, activation='relu'))
    model.add(Dense(10, activation='relu'))
    model.add(Dense(10, activation='relu'))
    model.add(Dense(1))
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

In [24]:
model = l3_regression_model()

In [25]:
model.fit(X_trainnorm, Y_trainnorm, validation_split=0.3, epochs=50, verbose=2)
Y_predicted = predict()
mse = calculate_mse()
report.loc[6] = ['D1', 'Single run, normalized data, 3 hidden layers, 50 epochs', round(mse,2)]
print('The mean square error' , round(mse))

Train on 504 samples, validate on 217 samples
Epoch 1/50
 - 16s - loss: 6799.5966 - val_loss: 5238.3572
Epoch 2/50
 - 0s - loss: 4262.7352 - val_loss: 3573.3790
Epoch 3/50
 - 0s - loss: 3127.9283 - val_loss: 2855.7434
Epoch 4/50
 - 0s - loss: 2558.2422 - val_loss: 2402.6572
Epoch 5/50
 - 0s - loss: 2173.0191 - val_loss: 2079.7626
Epoch 6/50
 - 0s - loss: 1882.3770 - val_loss: 1815.3323
Epoch 7/50
 - 0s - loss: 1633.6997 - val_loss: 1575.1028
Epoch 8/50
 - 0s - loss: 1424.2754 - val_loss: 1412.7439
Epoch 9/50
 - 0s - loss: 1298.5032 - val_loss: 1313.4940
Epoch 10/50
 - 0s - loss: 1209.1838 - val_loss: 1222.7679
Epoch 11/50
 - 0s - loss: 1113.0676 - val_loss: 1116.5485
Epoch 12/50
 - 0s - loss: 994.5780 - val_loss: 980.4439
Epoch 13/50
 - 0s - loss: 847.1121 - val_loss: 817.5950
Epoch 14/50
 - 0s - loss: 676.6691 - val_loss: 638.4497
Epoch 15/50
 - 0s - loss: 499.5398 - val_loss: 468.6604
Epoch 16/50
 - 0s - loss: 352.8935 - val_loss: 338.1836
Epoch 17/50
 - 0s - loss: 254.4557 - val_loss: 274.3409
Epoch 18/50
 - 0s - loss: 216.9359 - val_loss: 255.0054
Epoch 19/50
 - 0s - loss: 206.7059 - val_loss: 252.2018
Epoch 20/50
 - 0s - loss: 206.0024 - val_loss: 251.2074
Epoch 21/50
 - 0s - loss: 205.2688 - val_loss: 250.5036
Epoch 22/50
 - 0s - loss: 204.6330 - val_loss: 249.8575
Epoch 23/50
 - 0s - loss: 204.6003 - val_loss: 249.2215
Epoch 24/50
 - 0s - loss: 203.7264 - val_loss: 248.7254
Epoch 25/50
 - 0s - loss: 203.3102 - val_loss: 248.1236
Epoch 26/50
 - 0s - loss: 203.1151 - val_loss: 247.6549
Epoch 27/50
 - 0s - loss: 202.3916 - val_loss: 246.9204
Epoch 28/50
 - 0s - loss: 202.0227 - val_loss: 246.2803
Epoch 29/50
 - 0s - loss: 201.5224 - val_loss: 245.7569
Epoch 30/50
 - 0s - loss: 200.9310 - val_loss: 245.0929
Epoch 31/50
 - 0s - loss: 200.6557 - val_loss: 244.3962
Epoch 32/50
 - 0s - loss: 199.9509 - val_loss: 243.7526
Epoch 33/50
 - 0s - loss: 200.0011 - val_loss: 243.1171
Epoch 34/50
 - 0s - loss: 199.3350 - val_loss: 242.3785
Epoch 35/50
 - 0s - loss: 198.4137 - val_loss: 241.6368
Epoch 36/50
 - 0s - loss: 197.8785 - val_loss: 240.9914
Epoch 37/50
 - 1s - loss: 197.5430 - val_loss: 240.1613
Epoch 38/50
 - 1s - loss: 196.6915 - val_loss: 239.4708
Epoch 39/50
 - 0s - loss: 196.2639 - val_loss: 238.8147
Epoch 40/50
 - 0s - loss: 195.6996 - val_loss: 237.8667
Epoch 41/50
 - 0s - loss: 194.9768 - val_loss: 237.0976
Epoch 42/50
 - 0s - loss: 194.7823 - val_loss: 236.2529
Epoch 43/50
 - 0s - loss: 193.7010 - val_loss: 235.4370
Epoch 44/50
 - 0s - loss: 193.0919 - val_loss: 234.6785
Epoch 45/50
 - 0s - loss: 192.4256 - val_loss: 233.7713
Epoch 46/50
 - 0s - loss: 191.9468 - val_loss: 232.9113
Epoch 47/50
 - 0s - loss: 191.2884 - val_loss: 231.9323
Epoch 48/50
 - 0s - loss: 190.3778 - val_loss: 230.9926
Epoch 49/50
 - 0s - loss: 189.6494 - val_loss: 230.0380
Epoch 50/50
 - 0s - loss: 188.9681 - val_loss: 229.0533
The mean square error 199

In [26]:
msesnorm = []
for i in range(50):
    model = l3_regression_model()
    X_trainnorm, X_testnorm, Y_trainnorm, Y_testnorm = train_test_split(Xnorm, Y, test_size=0.3)
    model.fit(X_trainnorm, Y_trainnorm, validation_split=0.3, epochs=50, verbose=0)
    Y_predicted = predict()
    msenorm = calculate_mse()
    msesnorm.append(msenorm)
    print('Run', i + 1 , 'has an mse of', round(msenorm,2))

Run 1 has an mse of 107.69
Run 2 has an mse of 126.54
Run 3 has an mse of 132.02
Run 4 has an mse of 98.13
Run 5 has an mse of 234.52
Run 6 has an mse of 110.49
Run 7 has an mse of 72.25
Run 8 has an mse of 146.51
Run 9 has an mse of 82.71
Run 10 has an mse of 206.95
Run 11 has an mse of 183.44
Run 12 has an mse of 89.08
Run 13 has an mse of 137.65
Run 14 has an mse of 89.51
Run 15 has an mse of 90.08
Run 16 has an mse of 84.65
Run 17 has an mse of 111.61
Run 18 has an mse of 156.32
Run 19 has an mse of 97.75
Run 20 has an mse of 89.57
Run 21 has an mse of 189.33
Run 22 has an mse of 101.05
Run 23 has an mse of 105.99
Run 24 has an mse of 85.34
Run 25 has an mse of 119.39
Run 26 has an mse of 107.99
Run 27 has an mse of 107.41
Run 28 has an mse of 108.92
Run 29 has an mse of 113.79
Run 30 has an mse of 85.7
Run 31 has an mse of 84.53
Run 32 has an mse of 194.0
Run 33 has an mse of 171.54
Run 34 has an mse of 61.32
Run 35 has an mse of 68.11
Run 36 has an mse of 141.23
Run 37 has an mse of 100.41
Run 38 has an mse of 78.9
Run 39 has an mse of 88.33
Run 40 has an mse of 190.73
Run 41 has an mse of 129.41
Run 42 has an mse of 105.92
Run 43 has an mse of 114.15
Run 44 has an mse of 100.28
Run 45 has an mse of 118.26
Run 46 has an mse of 101.5
Run 47 has an mse of 93.72
Run 48 has an mse of 1375.71
Run 49 has an mse of 98.72
Run 50 has an mse of 93.77

In [27]:
msesmeannorm = mean(msesnorm)
msesstdnorm = stdev(msesnorm)
report.loc[7] = ['D2', 'Avarage of 50 runs, normalized data, 3 hidden layers, 50 epochs', round(msesmeannorm)]
print('The mean of mean square errors' , round(msesmeannorm,2))
print('Standard deviation of mean square errors' , round(msesstdnorm,2))

The mean of mean square errors 141.66
Standard deviation of mean square errors 182.14

In [28]:
report.style.hide_index()